### PR TITLE
fix) Passing sub op inputs intermittently broken; closes #238

### LINKED ISSUE #238: Passing sub op inputs intermittently broken
given:
```yaml
name: minimal-reproducible-example
input:
  in1:
    dir: {}
run:
  serial:
    - op: {pkg: {ref: sibling1}, inputs: {in1}, outputs: {out1}}
    - op: {pkg: {ref: sibling2}, inputs: {out1}}
```

expected:
1) run `minimal-reproducible-example`
2) sibling2 receives expected out1

actual:
1) run `minimal-reproducible-example`
2) sometimes sibling2 does not receive expected out1

### PR DESCRIPTION
**Pull request by chrisdostert**

### CODE REVIEW

File: node/core/containerCaller.go [hunk 1]
```diff
@@ -153,278 +175,164 @@ func (cc _containerCaller) Call(
...
-					Timestamp: time.Now().UTC(),
-					OutputInitialized: &model.OutputInitializedEvent{
-						Name:     name,
-						Value:    &model.Data{Dir: &dcgHostDirPath},
-						RootOpId: dcgContainerCall.RootOpId,
-						CallId:   dcgContainerCall.ContainerId,
-					},
-				})
+			if containerPath == dcgContainerDirPath {
+				// copy dcgHostDirPath before taking address; range vars have same address for every iteration
```
Comment (chrisdostert) [inline node/core/containerCaller.go]: @poppuyo this was the @#$@#$1@@3$!@

**Comment by chrisdostert** [comment]
approve
